export enum TypeUrlDev{
    portal = 'https://localhost:44326/api/',
    portalPROD = 'http://172.25.2.2:3000/api/'
}

export enum TypeServicio{
    login = 'Login/Loguear',
    camposFiltro = 'Colaboradores/GetCamposFiltros',
    colaboradores = 'Colaboradores/GetColaboradores',
    colaboradoresInterventor = 'Interventor/GetColaboradoresInterv',
    crearColaboradores = 'Colaboradores/CreateColaborador',
    crearColaboradoresInterv = 'Interventor/CreateColaboradorInterv',
    consultarColaboradores = 'Funcionario/GetNombresColaboradores',
    consultarColaborador = 'Funcionario/ObtenerInfoColaborador',
    consultarColaboradorCedula = 'Funcionario/ObtenerInfoColaboradorCC',
    getInfoColaborador = 'Colaboradores/GetInfoColaborador',
    getInfoColaboradorIntenventor = 'Interventor/GetInfoColaboradorInterv',
    getInfoColaboradorUsuario = 'Colaboradores/GetInfoColaboradorUsuario',
    getGerencias = 'Colaboradores/GetGerencias',
    getGetAreas = 'Colaboradores/GetAreas',
    getGetCCO = 'Colaboradores/GetCCO',
    GenerarReporteXlsx = 'Colaboradores/GenerarReporteXlsx',
    ActualizarEstadoColaborador = 'Colaboradores/ActualizarEstadoColaborador',
    putInfoColaborador = 'Colaboradores/ActualizarColaborador',
    putInfoColaboradorInterv = 'Interventor/ActualizarColaboradorInterv',
    PutInactivarColaborador = 'Colaboradores/InactivarColaborador',
    PutInactivarColaboradorInterv = 'Interventor/InactivarColaboradorInterv',
    PutActivarColaborador = 'Colaboradores/ActivarColaborador',
    PutActivarColaboradorInterv = 'Interventor/ActivarColaboradorInterv',
    getUsuarios ='Usuario/GetListarUsuarios',
    CrearUsuario ='Usuario/CrearUsuario',
    GetInfoUsuario ='Usuario/GetInfoUsuario',
    GetListarUsuariosAgregar = 'Usuario/GetListarUsuariosAregar',
    ActualizarUsuario ='Usuario/ActualizarUsuario',
    ActualizarClave='Usuario/ActualizarClave',
    GetRolesUsuario='Usuario/GetRolesUsuario',
    GetNombresFiltros='Filtros/GetNombresFiltros',
    GetNombresFiltroDet='Filtros/GetNombresFiltroDet',
    CrearFiltroDet='Filtros/CrearFiltroDet',
    ActualzarFiltroDet='Filtros/ActualzarFiltroDet',
    GetCamposEstado='Colaboradores/GetCamposEstado',
    AprobarRechazarColaborador='Colaboradores/AprobarRechazarColaborador',
    GetAplicativos='Colaboradores/GetAplicativos',
    GetMenu='Menu/ConsultarMenuPerfil'
}